// import 'package:ecommerce/admin/blocs/add_product_bloc/add_product_bloc.dart';
// import 'package:flutter/material.dart';
// import 'package:flutter_bloc/flutter_bloc.dart';
// import 'package:product_repository/product_repository.dart';

// class AddProductScreen extends StatefulWidget {
//   const AddProductScreen({super.key});

//   @override
//   _AddProductScreenState createState() => _AddProductScreenState();
// }

// class _AddProductScreenState extends State<AddProductScreen> {
//   final _nameController = TextEditingController();
//   final _descriptionController = TextEditingController();
//   final _categoryController = TextEditingController();
//   final _priceController = TextEditingController();
//   final _discountController = TextEditingController();
//   final _imageUrlController = TextEditingController();
//   bool _isAvailable = true;

//   @override
//   void dispose() {
//     // Dispose of controllers to prevent memory leaks
//     _nameController.dispose();
//     _descriptionController.dispose();
//     _categoryController.dispose();
//     _priceController.dispose();
//     _discountController.dispose();
//     _imageUrlController.dispose();
//     super.dispose();
//   }

//   @override
//   Widget build(BuildContext context) {
//     return BlocProvider(
//       create: (context) => AddProductBloc(FirebaseProductRepo()),
//       child: Scaffold(
//         appBar: AppBar(title: const Text('Add Product')),
//         body: Padding(
//           padding: const EdgeInsets.all(16.0),
//           child: Column(
//             children: [
//               TextField(
//                 controller: _nameController,
//                 decoration: const InputDecoration(labelText: 'Name'),
//               ),
//               TextField(
//                 controller: _descriptionController,
//                 decoration: const InputDecoration(labelText: 'Description'),
//               ),
//               TextField(
//                 controller: _categoryController,
//                 decoration: const InputDecoration(labelText: 'Category'),
//               ),
//               TextField(
//                 controller: _priceController,
//                 decoration: const InputDecoration(labelText: 'Price'),
//                 keyboardType: TextInputType.number,
//               ),
//               TextField(
//                 controller: _discountController,
//                 decoration: const InputDecoration(labelText: 'Discount'),
//                 keyboardType: TextInputType.number,
//               ),
//               TextField(
//                 controller: _imageUrlController,
//                 decoration: const InputDecoration(labelText: 'Image URL'),
//               ),
//               SwitchListTile(
//                 title: const Text('Available'),
//                 value: _isAvailable,
//                 onChanged: (value) {
//                   setState(() {
//                     _isAvailable = value;
//                   });
//                 },
//               ),
//               const SizedBox(height: 20),

//               ElevatedButton(
//                 onPressed: () {
//                   final product = Product(
//                     pId: '', // To be generated by Firestore
//                     name: _nameController.text,
//                     description: _descriptionController.text,
//                     category: _categoryController.text,
//                     price: int.tryParse(_priceController.text) ?? 0,
//                     discount: int.tryParse(_discountController.text) ?? 0,
//                     image: _imageUrlController.text,
//                     isAvailable: _isAvailable,
//                   );
//                   context
//                       .read<AddProductBloc>()
//                       .add(AddProductSubmitted(product));
//                 },
//                 child: const Text('Add Product'),
//               )
//               // BlocBuilder<AddProductBloc, AddProductState>(
//               //   builder: (context, state) {
//               //     if (state is AddProductLoading) {
//               //       return const Center(child: CircularProgressIndicator());
//               //     }
//               //     return ElevatedButton(
//               //       onPressed: () {
//               //         final product = Product(
//               //           pId: '', // To be generated by Firestore
//               //           name: _nameController.text,
//               //           description: _descriptionController.text,
//               //           category: _categoryController.text,
//               //           price: int.tryParse(_priceController.text) ?? 0,
//               //           discount: int.tryParse(_discountController.text) ?? 0,
//               //           image: _imageUrlController.text,
//               //           isAvailable: _isAvailable,
//               //         );
//               //         context.read<AddProductBloc>().add(AddProductSubmitted(product));
//               //       },
//               //       child: const Text('Add Product'),
//               //     );
//               //   },
//               // ),
//             ],
//           ),
//         ),
//       ),
//     );
//   }
// }
