// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8NkXN0pZ5brksE3b3v2bzbFMgQ9Spbc',
    appId: '1:1569259496:android:dfabaae797de64a5e6ae5d',
    messagingSenderId: '1569259496',
    projectId: 'ecommerce-50a07',
    storageBucket: 'ecommerce-50a07.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq9gUQ2gImEVEjl3fW1ygnW-aemCW7WsQ',
    appId: '1:1569259496:web:2550629b44725e9de6ae5d',
    messagingSenderId: '1569259496',
    projectId: 'ecommerce-50a07',
    authDomain: 'ecommerce-50a07.firebaseapp.com',
    storageBucket: 'ecommerce-50a07.appspot.com',
    measurementId: 'G-FWJTVSMEMX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwskxLay5yRDEG7_PRVd0mvR0wlmUtEB8',
    appId: '1:1569259496:ios:9fec174a34056b53e6ae5d',
    messagingSenderId: '1569259496',
    projectId: 'ecommerce-50a07',
    storageBucket: 'ecommerce-50a07.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwskxLay5yRDEG7_PRVd0mvR0wlmUtEB8',
    appId: '1:1569259496:ios:9fec174a34056b53e6ae5d',
    messagingSenderId: '1569259496',
    projectId: 'ecommerce-50a07',
    storageBucket: 'ecommerce-50a07.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq9gUQ2gImEVEjl3fW1ygnW-aemCW7WsQ',
    appId: '1:1569259496:web:2550629b44725e9de6ae5d',
    messagingSenderId: '1569259496',
    projectId: 'ecommerce-50a07',
    authDomain: 'ecommerce-50a07.firebaseapp.com',
    storageBucket: 'ecommerce-50a07.appspot.com',
    measurementId: 'G-FWJTVSMEMX',
  );

}